import type { StepOrderTriple } from "./types";

// Linear project sequence: the order a real project actually clears these submissions in,
// regardless of which governing body handles each one. Each entry is
// [stageId, agencyId, submissionCode] — the stageId is only the default grouping; a step's
// live stage can be overridden per-project (project_step_stage) once dragged.
export const STEP_ORDER: StepOrderTriple[] = [
  ["pre-design", "admin", "INTAKE"],
  ["pre-design", "corenet", "TEAM"],
  ["pre-design", "admin", "SITEVISIT"],
  ["pre-design", "site", "PREINV"],
  ["pre-design", "sla", "SURVEY"],
  ["concept", "admin", "DESIGN"],
  ["concept", "ura", "SUB"],
  ["concept", "ura", "OP"],
  ["concept", "ura", "CONSV"],
  ["concept", "admin", "CONSULTANTS"],
  ["dev", "admin", "DEV"],
  ["dev", "ura", "DC/DP"],
  ["dev", "nparks", "TREE"],
  ["dev", "nea", "ENV"],
  ["detailed", "ura", "PP"],
  ["detailed", "ura", "PL"],
  ["detailed", "lta", "ACCESS"],
  ["detailed", "lta", "TIA"],
  ["detailed", "pub", "SS"],
  ["detailed", "pub", "SW"],
  ["detailed", "scdf", "FS"],
  ["detailed", "nparks", "GREEN"],
  ["detailed", "imda", "COPIF"],
  ["detailed", "tfcc", "PLAN"],
  ["detailed", "admin", "PCSUMS"],
  ["detailed", "admin", "TENDERSET"],
  ["tender", "bca", "BP"],
  ["tender", "bca", "ST"],
  ["tender", "admin", "TENDER"],
  ["tender", "admin", "AWARD"],
  ["construction", "nea", "ASBESTOS"],
  ["construction", "bca", "PERMIT"],
  ["construction", "bca", "DEMO"],
  ["construction", "iras", "NUMBERING"],
  ["construction", "mom", "WSH"],
  ["construction", "utilities", "ELEC"],
  ["construction", "corenet", "LEW"],
  ["construction", "utilities", "TEST"],
  ["construction", "utilities", "GAS"],
  ["construction", "tfcc", "FIBRE"],
  ["construction", "tp", "TTM"],
  ["top", "pub", "WS"],
  ["top", "pub", "CLR"],
  ["top", "scdf", "FSC/TFP"],
  ["top", "bca", "TOP"],
  ["csc", "bca", "CSC"],
  ["csc", "iras", "PTAX"],
  ["top", "admin", "TOPDOCS"],
];
